# Generated by Django 5.0.4 on 2024-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0002_signup_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
    ]
